export const checkboxes = [
    {
      heading: "Sort Jobs By",
      values: [
        { key: "Date Posted", value: "Date Posted" },
        { key: "Relevance", value: "Relevance" },
      ],
    },
    {
      heading: "Job Model",
      values: [
        { key: "Hybrid", value: "Hybrid" },
        { key: "Remote", value: "Remote" },
        { key: "On-Site", value: "On-Site" },
      ],
    },
    {
      heading: "Employment Type",
      values: [
        { key: "Full-Time", value: "Full-Time" },
        { key: "Part-Time", value: "Part-Time" },
        { key: "Contract", value: "Contract" },
        { key: "Internship", value: "Internship" },
      ],
    },
    {
      heading: "Experience",
      values: [
        { key: "EntryLevel", value: "EntryLevel" },
        { key: "1 - 3 Years", value: 1 },
        { key: "3 - 5 Years", value: 3 },
        { key: "5 - 10 Years", value: 5 },
        { key: "10+ Years", value: 10 },
      ],
    },
    {
      heading: "Salary Type",
      values: [
        { key: "Fixed Salary", value: "Fixed Salary" },
        { key: "$50000 - $70000 Annual", value: 50000 },
        { key: "$70000 - $100,000 Annual", value: 70000 },
        { key: "$100,000 + Annual", value: 100000 },
      ],
    },
  ];
  
export const DataArray = [
    {
      imageurl: "",
      title: "Senior System's Design Engineer",
      name: "Microsoft",
      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "$150,000",
      JobModel: "Remote",
      EmploymentType: "Full-Time",
      Experience: 3,
      SalaryRate:"Monthly",
      ApplicationDeadline: "07/31/2023",
      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
    {
      imageurl: "",
      SalaryRate:"Monthly",

      title: "Senior System's Design Engineer",
      name: "Microsoft",
      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "150,000$",
      JobModel: "Hybrid",
      EmploymentType: "Full-Time",
      Experience: 3,
      ApplicationDeadline: "07/25/2023",
      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
    {
      imageurl: "",
      title: "Senior System's Design Engineer",
      name: "Microsoft",
      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "150,000$",
      JobModel: "Remote",
      EmploymentType: "Full-Time",
      Experience: 3,
      SalaryRate:"Monthly",

      ApplicationDeadline: "07/31/2023",
      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
    {
      imageurl: "",
      SalaryRate:"Monthly",

      title: "Senior System's Design Engineer",
      name: "Microsoft",
      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "150,000$",
      JobModel: "Remote",
      EmploymentType: "Full-Time",
      Experience: 3,
      ApplicationDeadline: "07/31/2023",
      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
    {
      imageurl: "",
      title: "Senior System's Design Engineer",
      name: "Microsoft",
      SalaryRate:"Monthly",

      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "150,000$",
      JobModel: "Remote",
      EmploymentType: "Full-Time",
      Experience: 3,
      ApplicationDeadline: "07/31/2023",
      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
    {
      imageurl: "",
      title: "Senior System's Design Engineer",
      name: "Microsoft",
      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "150,000$",
      JobModel: "Remote",
      EmploymentType: "Full-Time",
      Experience: 3,
      ApplicationDeadline: "07/31/2023",
      SalaryRate:"Monthly",

      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
    {
      imageurl: "",
      title: "Senior System's Design Engineer",
      SalaryRate:"Monthly",

      name: "Microsoft",
      tags: "Urgently Hiring",
      location: "Redmond, Washington State",
      Salary: "150,000$",
      JobModel: "Remote",
      EmploymentType: "Full-Time",
      Experience: 3,
      ApplicationDeadline: "07/31/2023",
      DesiredSkills: [
        "Technical knowledge",
        "System Architecture",
        "Risk Management",
        "Project Management",
        "Quality Focus",
        "Q/A Testing",
        "LeaderShip",
        "Product Design",
      ],
    },
  ];