import Context from "@/context/context";
import store from "@/Reudx/store";
import "@/styles/globals.css";
import { theme } from "@/theme/theme";
import { ChakraProvider } from "@chakra-ui/react";
import "@fontsource/open-sans";
import Head from "next/head";
import { Provider } from "react-redux";
import { Role_context } from "../context/context"; // Corrected the import as needed

export default function App({ Component, pageProps }) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>JOBREEF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Role_context.Provider value={{ company: true }}>
      <Context>
        <Provider store={store}>
          <Component {...pageProps} />
        </Provider>
      </Context>
      </Role_context.Provider>
    </ChakraProvider>
  );
}

















// import Context from "@/context/context";
// import store from "@/Reudx/store";
// import "@/styles/globals.css";
// import { theme } from "@/theme/theme";
// import { ChakraProvider } from "@chakra-ui/react";
// import "@fontsource/open-sans";
// import Head from "next/head";
// import { Provider } from "react-redux";
// export default function App({ Component, pageProps }) {
//   return (
//     <ChakraProvider theme={theme}>
//       <Head>
//         <title>OBREEF</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Context>
//         <Provider store={store}>
//           <Component {...pageProps} />
//         </Provider>
//       </Context>
//     </ChakraProvider>
//   );
// }