const endPoints = {
  user: "user",
  verifyOtp:'verify-otp',
  company:'company',
  employee:'employee',
  login:"login",
  resendOtp:"resend-otp",
  changePassword:"change-password",
  emailPreferences:"emailPreferences",
  workExperience:"workexperience",
  education:"education",
  certification:"certification",
  skills:"skills",
  attachment:"attachment",
  achievement:"achievement",
  jobs:"jobs",
  companyJobs:"companyJobs",
  appliedJobs:"appliedJobs",
  teamMember:"team-member",
  applications:"applications",
  matchCandidate:"match-candidate",
  employeeSkills:"employee-skills",
  search:"search",
};
export default endPoints;
