const registration = {
  firstName: "",
  lastName: "",
  email: "",
  isCompany: true,
  password: "",
  confirmPassword: "",
  otp: "",
  userId: null,
};
let company = {
  companyName: "",
  industry: "",
  directory: "",
  noOfEmployees: "",
  yearEstablished: "",
  webUrl: "",
  telePhone: "",
  description: "",
  country: "",
  province: "",
  city: "",
  address: "",
  loading: false,
  platform: "",
  // telePhone:"",
  link: "",
  logo: false,
  socialLinks: [
    {
      platform: "",
      link: "",
    },
  ],
};
const employee = {
  country: "",
  state: "",
  province: "",
  city: "",
  number: "",
  description: "",
  workExperience: false,
  education: false,
  attachments: {
    resume: [],
    additional: [],
  },
  achievement: false,
  certification: false,
  skills: false,
  // id: "657c281299882859c18f6672",
  id: null,
};
const workExperience = {
  country: "",
  province: "",
  city: "",
  address: "",
  companyName: "",
  designation: "",
  startDate: null,
  endDate: null,
  currentlyWorking: false,
  employeeType: "",
  jobFamily: "",
  jobSummary: "",
};
const education = {
  schoolName: "",
  diploma: "",
  currentlyEnrolled: false,
  startDate: null,
  endDate: null,
  country: "",
  province: "",
  city: "",
  address: "",
  gpa: "",
  description: "",
};
const certification = {
  certificateName: "",
  organizationName: "",
  certificateId: "",
  issuedOn: null,
  noExpiry: false,
  validUntil: null,
  certificateMedia: [],
};
const achievement = {
  name: "",
  issueOrganization: "",
  issuedOn: "",
  media: [],
};
const job = {
  title: "",
  employmentType: "",
  applicationDeadline:null,
  locationType: "",
  jobDescription: "",
  opening: "",
  minimumEducation: "",
  yearsOfExperience: "",
  jobFamily: "",
  minimumSalary: "",
  maximumSalary: "",
  country: "",
  state: "",
  seniorityLevel:"",
  city: "",
  address: "",
  desiredSkills: "",
  province:'',
  tags: [],
  externalURL:"",
  applicationType: "",
  rate: "",
  screeningQuestions: [
    {
      question: "",
      type: "",
    },
  ],
};
const skills = [{ name: "", level: "" }];
export {
  skills,
  certification,
  registration,
  company,
  achievement,
  job,
  education,
  employee,
  workExperience,
};
