const registration = {
  firstName: "",
  lastName: "",
  email: "",
  isCompany: true,
  password: "",
  confirmPassword: "",
  otp: "",
  userId: null,
};
let company = {
  companyName: "",
  industry: "",
  directory: "",
  noOfEmployees: "",
  yearEstablished: "",
  webUrl: "",
  telePhone: "",
  description: "",
  country: "",
  province: "",
  city: "",
  address: "",
  loading: false,
  platform: "",
  link: "",
  logo: false,
  socialLinks: [
    {
      platform: "",
      link: "",
    },
  ],
};
const employee = {
  country: "",
  state: "",
  province: "",
  city: "",
  number: "",
  description: "",
  workExperience: false,
  education: false,
  attachments: {
    resume: [],
    additional: [],
  },
  achievement: false,
  certification:false,
  skills: false,
  // id: "65714f5716dc9f3d6dc313f5",
  id: null,
};
const workExperience = {
  country: "",
  province: "",
  city: "",
  address: "",
  companyName: "",
  designation: "",
  startDate: null,
  endDate: null,
  currentlyWorking: false,
  employeeType: "",
  jobFamily: "",
  jobSummary: "",
};
const education = {
  schoolName: "",
  diploma: "",
  currentlyEnrolled: false,
  startDate: null,
  endDate: null,
  country: "",
  province: "",
  city: "",
  address: "",
  gpa: "",
  description: "",
};
const certification = {
  certificateName: "",
  organizationName: "",
  certificateId: "",
  issuedOn: null,
  noExpiry: false,
  validUntil: null,
  certificateMedia: [],
};
const achievement = {
  name: "",
  issueOrganization: "",
  issuedOn: "",
  media: [],
};
const skills = [{ name: "", level: "" }];
export {
  skills,
  certification,
  registration,
  company,
  achievement,
  education,
  employee,
  workExperience,
};
